name: Create Game

on:
  workflow_dispatch:
    inputs:
      white_username:
        required: true
        type: string
      black_username:
        required: true
        type: string
  discussion:
    types: [created]

permissions:
  actions: write
  contents: write
  discussions: write

jobs:
  create-game:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          corepack enable
          yarn install

      - name: Create a Game
        env:
          DISCUSSION_ID: ${{ github.event.discussion.id }}
          DISCUSSION_TITLE: ${{ github.event.discussion.title }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make create-game

      - name: Trigger Main Workflow
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run main.yml --ref main
